const supabaseUrl = "https://dtrokaqhgupubrofnndx.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0cm9rYXFoZ3VwdWJyb2ZubmR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0Mjk5OTYsImV4cCI6MjA4MDAwNTk5Nn0.JZ11fSKeObYIH-Z3Rt2S8dcS4gIN9jmUp7sMRdcUwko";

const supabase = supabase.createClient(supabaseUrl, supabaseKey);
